---------------------------SELECT-----------------------------------

--SELECT ALL DATA
SELECT * FROM CUSTOMER

--SELECT CITY
SELECT CITY FROM CUSTOMER

--SELECT CUSTOMER NAME AND DISTRICT
SELECT CUSTOMERNAME, DISTRICT FROM CUSTOMER

---------------------------INSERT-----------------------------------

--INSERT
INSERT INTO CUSTOMER
(CUSTOMERNAME, CITY, DISTRICT, BIRTHDATE, GENDER, AGE)
VALUES
('Faruk YILMAZ', 'Sivas', 'Zara', '1994.05.13', 'E', 28)

---------------------------UPDATE-----------------------------------

--UPDATE AGE
UPDATE CUSTOMER SET AGE=DATEDIFF(YEAR, BIRTHDATE, GETDATE())

UPDATE CUSTOMER SET AGE=AGE-1

UPDATE CUSTOMER SET AGE=AGE+1

-----------------------DELETE, TRUNCATE AND DROP---------------------------

--CREATE A BACKUP TABLE FROM CUSTOMER AND THEN DELETE IT
SELECT * INTO CUSTOMER_BACKUP FROM CUSTOMER

SELECT * FROM CUSTOMER_BACKUP

DELETE FROM CUSTOMER_BACKUP

DROP TABLE CUSTOMER_BACKUP

--TRUNCATE TABLE
TRUNCATE TABLE CUSTOMER_BACKUP

---------------------------WHERE-----------------------------------

--SELECT CUSTERMERNAME = Salih FAYDALI
SELECT* FROM CUSTOMER
WHERE CUSTOMERNAME='Salih FAYDALI'

--SELECT ID=20
SELECT * FROM CUSTOMER
WHERE ID=20

--SELECT CITY=ISTANBUL
SELECT * FROM CUSTOMER
WHERE CITY='İstanbul'


--SELECT AGE > 55
SELECT * FROM CUSTOMER
WHERE AGE>55

--SELECT 50 => AGE => 55
SELECT * FROM CUSTOMER
WHERE AGE BETWEEN 50 AND 55

SELECT * FROM CUSTOMER 
WHERE BIRTHDATE BETWEEN '1980-01-01' AND '1981-01-01'

--SELECT CUSTOMER NAME STARTSWITH 'Ali'
SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE 'Ali%'

--SELECT CUSTOMER NAME ENDING WITH 'ALI'
SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE '%ALI'

--SELECT CUSTOMER NAME CONTAINS 'ali'
SELECT * FROM CUSTOMER
WHERE CUSTOMERNAME LIKE '%ali%'

--SELECT CUSTOMER CITY='İstanbul' AND DISTRICT IN 'Esenler' or 'Kadıköy'
SELECT * FROM CUSTOMER
WHERE CITY='İstanbul' AND DISTRICT IN ('Kadıköy', 'Esenler')

--SELECT CUSTOMER CITY='Isparta' AND DISTRICT NOT IN 'Gelendost' and 'Yalvaç'
SELECT * FROM CUSTOMER
WHERE CITY='Isparta' AND DISTRICT NOT IN ('Gelendost', 'Yalvaç')

-- DELETE CUSTOMER ID=1
DELETE FROM CUSTOMER
WHERE ID=1

---------------------------UPDATE-----------------------------------

--UPDATE CUSTOMER GENDER 
UPDATE CUSTOMER SET GENDER='ERKEK'
WHERE GENDER='E'

UPDATE CUSTOMER SET GENDER='KADIN'
WHERE GENDER='K'

SELECT * FROM CUSTOMER

-----------------------------AND/OR-----------------------------------

SELECT * FROM CUSTOMER
WHERE CITY='İstanbul' AND CUSTOMERNAME LIKE '%ali%'

SELECT * FROM CUSTOMER
WHERE CITY='Isparta' OR CITY='BURDUR'

-----------------------------DISTINCT-----------------------------------

SELECT DISTINCT CITY FROM CUSTOMER

SELECT DISTINCT DISTRICT FROM CUSTOMER

-----------------------------ORDER BY-----------------------------------

SELECT * FROM CUSTOMER
ORDER BY CUSTOMERNAME

SELECT * FROM CUSTOMER
ORDER BY CITY

SELECT * FROM CUSTOMER
ORDER BY CITY, DISTRICT

SELECT * FROM CUSTOMER
ORDER BY CITY, DISTRICT DESC

-----------------------------TOP-----------------------------------

SELECT TOP 10 * FROM CUSTOMER
WHERE AGE > 50

SELECT TOP 15 * FROM CUSTOMER
WHERE AGE > 50

SELECT TOP 15 PERCENT * FROM CUSTOMER
WHERE AGE > 50










