-- CREATE HR DATABASE
CREATE DATABASE HR

-- CREATE DEPARTMENT TABLE
CREATE TABLE DEPARTMENTS (
	ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	DEPARTMENT VARCHAR(50)
)

-- CREATE POSITION TABLE
CREATE TABLE POSITIONS (
	ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	POSITION VARCHAR(50),
)

-- CREATE PERSON TABLE
CREATE TABLE PERSONS (
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	CODE VARCHAR(50),
	TCNUMBER VARCHAR(11),
	NAME_ VARCHAR(50),
	SURNAME VARCHAR(50),
	GENDER VARCHAR(1),
	BIRTHDATE DATE,
	INDATE DATE,
	OUTDATE DATE,
	DEPARTMENTID INT,
	POSITIONID INT,
	PARENTPOSITIONID INT,
	MANAGERID INT,
	TELNR VARCHAR(12),
	SALARY FLOAT
)
