--CREATE A DATABASE CALLED FLO
CREATE DATABASE FLO

--CREATE TABLE
CREATE TABLE CUSTOMERS(
 MASTER_ID VARCHAR(100),
 ORDER_CHANNEL VARCHAR(20),
 LAST_ORDER_CHANNEL VARCHAR(20),
 FIRST_ORDER_DATE DATETIME,
 LAST_ORDER_DATE DATETIME,
 LAST_ORDER_DATE_ONLINE DATE,
 LAST_ORDER_DATE_OFFLINE DATE,
 ORDER_NUM_TOTAL_ONLINE INT,
 ORDER_NUM_TOTAL_OFFLINE INT,
 CUSTOMER_VALUE_TOTAL_OFFLINE FLOAT,
 CUSTOMER_VALUE_TOTAL_ONLINE FLOAT,
 INTERESTED_CATEGORY VARCHAR(100),
 STORE_TYPE VARCHAR(10)
)